return {
  {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    event = 'BufReadPost',
    config = function()
      require('nvim-treesitter.configs').setup({
        ensure_installed = {
          'bash',
          'c',
          'cpp',
          'css',
          'dart',
          'diff',
          'dot',
          'git_rebase',
          'gitattributes',
          'gitcommit',
          'go',
          'help',
          'html',
          'java',
          'javascript',
          'json',
          'jsonc',
          'kotlin',
          'lua',
          'proto',
          'python',
          'query',
          'scss',
          'typescript',
          'vim',
          'yaml',
        },
        highlight = { enable = true },
        query_linter = {
          enable = true,
          use_virtual_text = true,
          lint_events = { 'BufWrite', 'CursorHold' },
        },
      })
    end,
  },
  {
    'nvim-treesitter/playground',
    dependencies = { 'nvim-treesitter/nvim-treesitter' },
    cmd = { 'TSPlaygroundToggle', 'TSHighlightCapturesUnderCursor' },
  },
}
